### ISSUE TITLE
CLI command for creating Media Services resource appears to be missing

### ISSUE THREAD

**Issue by shammyowens** [MicrosoftDocs/azure-media-services#10]
There should be a command under

_The following Azure CLI command creates a new Media Services account._

but it is blank

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ad8a938-fae2-e57a-d71e-70f870654d1c
* Version Independent ID: 2ad8a938-fae2-e57a-d71e-70f870654d1c
* Content: [Create an Azure Media Services account](https://learn.microsoft.com/en-us/azure/media-services/latest/account-create-how-to?tabs=portal)
* Content Source: [media-services/latest/account-create-how-to.md](https://github.com/MicrosoftDocs/azure-media-services/blob/main/media-services/latest/account-create-how-to.md)
* Service: **media-services**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by IngridAtMicrosoft** [comment]
Thank you @shammyowens! I will take a look today.

**Comment by IngridAtMicrosoft** [comment]
@shammyowens Please close this issue.
