### ISSUE TITLE
Microsoft.Azure.Management.Media is depreciated

### ISSUE THREAD

**Issue by rdurrance** [MicrosoftDocs/azure-media-services#11]
Hello,
Since Microsoft.Azure.Management.Media is depreciated, do you have examples with the recommended Azure.ResourceManager.Media to create an asset and then a job for Media Services? 
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6be8ca14-15b6-379f-9a15-4c69535054d1
* Version Independent ID: 6be8ca14-15b6-379f-9a15-4c69535054d1
* Content: [Upload content to an asset CLI](https://learn.microsoft.com/en-us/azure/media-services/latest/asset-create-asset-how-to?amspage=assets-concept&tabs=portal)
* Content Source: [media-services/latest/asset-create-asset-how-to.md](https://github.com/MicrosoftDocs/azure-media-services/blob/main/media-services/latest/asset-create-asset-how-to.md)
* Service: **media-services**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by IngridAtMicrosoft** [comment]
Hello @rdurrance,
Please see https://github.com/Azure-Samples/media-services-v3-dotnet/tree/track2/Assets.  We are in the process of updating the .Net samples.

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by IngridAtMicrosoft** [comment]
@rdurrance Please close this issue.
