### ISSUE TITLE
Suggested .NET package for Media Services is deprecated

### ISSUE THREAD

**Issue by TheAustinG** [MicrosoftDocs/azure-media-services#12]
I am in the process of upgrading our Media Services v2 to v3 of the API. In this guide, it says you need to install the latest version of `Microsoft.Azure.Management.Media`. That package has been deprecated though, according to the [NuGet page](https://www.nuget.org/packages/Microsoft.Azure.Management.Media).

The NuGet page suggests you should install [Azure.ResourceManager.Media](https://www.nuget.org/packages/Azure.ResourceManager.Media/)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 35b57040-b37c-e542-7de2-27c64730627f
* Version Independent ID: 35b57040-b37c-e542-7de2-27c64730627f
* Content: [Media Services v2 to v3 migration setup](https://learn.microsoft.com/en-us/azure/media-services/latest/migrate-v-2-v-3-migration-setup?tabs=rest)
* Content Source: [media-services/latest/migrate-v-2-v-3-migration-setup.md](https://github.com/MicrosoftDocs/azure-media-services/blob/main/media-services/latest/migrate-v-2-v-3-migration-setup.md)
* Service: **media-services**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by IngridAtMicrosoft** [comment]
@TheAustinG Thank you for pointing that out.  Engineering has been contacted and the document will be updated. Very pleased to hear that you are migrating from v2 to v3! Please contact support if you need assistance.

**Comment by IngridAtMicrosoft** [comment]
@TheAustinG Please close this issue.
