### ISSUE TITLE
Bug in sample code: < script src="js/dash.all.js"></script>

### ISSUE THREAD

**Issue by dnfaulkner** [MicrosoftDocs/azure-media-services#13]
[Enter feedback here]
There is a bug in the sample code in this line:
< script src="js/dash.all.js"></script>
Change it to:
<script src="js/dash.all.js"></script>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02917aac-d956-a251-d780-f19d5407f030
* Version Independent ID: 02917aac-d956-a251-d780-f19d5407f030
* Content: [Embedding a MPEG-DASH Adaptive Streaming Video in an HTML5 Application with DASH.js](https://learn.microsoft.com/en-us/azure/media-services/previous/media-services-embed-mpeg-dash-in-html5)
* Content Source: [media-services/previous/media-services-embed-mpeg-dash-in-html5.md](https://github.com/MicrosoftDocs/azure-media-services/blob/main/media-services/previous/media-services-embed-mpeg-dash-in-html5.md)
* Service: **media-services**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by IngridAtMicrosoft** [comment]
Thanks @dnfaulkner! I will take care of that right away.  However, I would like to point out that this document is in the v2 version of Media Services.  We are deprecating that version in 2024, so if you are planning development, please look at the [v3](https://learn.microsoft.com/en-us/azure/media-services/latest/media-services-overview) version, [3rd party player samples](https://github.com/Azure-Samples/media-services-3rdparty-player-samples) and the [code samples](https://learn.microsoft.com/en-us/azure/media-services/latest/samples-overview?tabs=node) here.  If you need to migrate from v2 to v3, we have provided a [migration guide](https://learn.microsoft.com/en-us/azure/media-services/latest/migrate-v-2-v-3-migration-introduction).

**Comment by dnfaulkner** [comment]
Wow! That was quick! Thanks for the heads-p on v3.

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by dnfaulkner** [comment]
Done
