### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by joneswah** [MicrosoftDocs/azure-media-services#14]
There is a broken link under the:
How-Tos and Tutorials
[Create a streaming locator](https://learn.microsoft.com/en-us/streaming-locator-create-how-to?amspage=stream-streaming-locators-concept)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5c3ee0d-bd55-746c-3850-64a6f3c88ee2
* Version Independent ID: c5c3ee0d-bd55-746c-3850-64a6f3c88ee2
* Content: [Streaming Locators in Azure Media Services](https://learn.microsoft.com/en-us/azure/media-services/latest/stream-streaming-locators-concept)
* Content Source: [media-services/latest/stream-streaming-locators-concept.md](https://github.com/MicrosoftDocs/azure-media-services/blob/main/media-services/latest/stream-streaming-locators-concept.md)
* Service: **media-services**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by IngridAtMicrosoft** [comment]
Thank you @joneswah!
