### ISSUE TITLE
Wrong link to monitor events using Azure CLI

### ISSUE THREAD

**Issue by mariakbf** [MicrosoftDocs/azure-media-services#15]
Broken link in the **Monitoring** section, under the question **How do I monitor my Media Services live event?** (https://learn.microsoft.com/en-us/azure/media-services/latest/frequently-asked-questions#how-do-i-monitor-my-media-services-live-event)
The link for "Create and monitor Media Services events with Event Grid using the Azure CLI" directs to "Create and monitor Media Services events with Event Grid using the Azure portal"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: abfe2eac-8c03-a48f-5ff8-a812f8746d93
* Version Independent ID: abfe2eac-8c03-a48f-5ff8-a812f8746d93
* Content: [Azure Media Services FAQ](https://learn.microsoft.com/en-us/azure/media-services/latest/frequently-asked-questions#what-is-a-media-services-streaming-endpoint)
* Content Source: [media-services/latest/frequently-asked-questions.yml](https://github.com/MicrosoftDocs/azure-media-services/blob/main/media-services/latest/frequently-asked-questions.yml)
* Service: **media-services**
* GitHub Login: @IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
@mariakbf Thanks for you input. I will take a look at the broken link.
