### ISSUE TITLE
Dead Link under Samples section

### ISSUE THREAD

**Issue by JakeCroz1** [MicrosoftDocs/azure-media-services#16]
**Issue**: The "Samples" section of the documentation contains a dead link. The dead link is "compare the V2 and V3 code in the code samples".
**Dead link locations**:
- Microsoft Docs with Dead link: [Encoding migration guidance](https://learn.microsoft.com/en-us/azure/media-services/latest/migrate-v-2-v-3-migration-scenario-based-encoding#samples)
- GitHub Content with Dead link:  [migrate-v-2-v-3-migration-scenario-based-encoding.md#samples](https://github.com/MicrosoftDocs/azure-media-services/blob/main/media-services/latest/migrate-v-2-v-3-migration-scenario-based-encoding.md#samples)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0fbee43b-5333-d042-eb5a-e5cc0c67673a
* Version Independent ID: 0fbee43b-5333-d042-eb5a-e5cc0c67673a
* Content: [Encoding migration guidance](https://learn.microsoft.com/en-us/azure/media-services/latest/migrate-v-2-v-3-migration-scenario-based-encoding)
* Content Source: [media-services/latest/migrate-v-2-v-3-migration-scenario-based-encoding.md](https://github.com/MicrosoftDocs/azure-media-services/blob/main/media-services/latest/migrate-v-2-v-3-migration-scenario-based-encoding.md)
* Service: **media-services**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by IngridAtMicrosoft** [comment]
Thank you @JakeCroz1 this will be addressed today. #please-close

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by JakeCroz1** [comment]
Job well done.
