### ISSUE TITLE
"properties/created" not "properties.created"

### ISSUE THREAD

**Issue by Bellarmine-Head** [MicrosoftDocs/azure-media-services#17]
[The table at the bottom of this page ](https://learn.microsoft.com/en-us/azure/media-services/latest/filter-order-page-entities-how-to#filtering-and-ordering-options-of-entities) says that the `Property name` is:-

> properties.something

e.g.

> properties.created

But in my attempt to order media assets, `properties.created` caused the request to fail, while `properties/created` works:-

```csharp
// Reference:
// https://learn.microsoft.com/en-us/azure/media-services/latest/filter-order-page-entities-how-to

var mediaAssets = _mediaServicesAccountResource.GetMediaAssets().GetAllAsync(
    filter: null,
    top: null,
    orderby: "properties/created desc");

return await mediaAssets.Where(asset => asset.HasData).Select(MediaAssetResourceToVideoAssetSummary).ToArrayAsync();
```

The error message of the exception if I use `properties.created` is:-

```
"The child type 'properties.created' in a cast was not an entity type. Casts can only be performed on entity types.
Status: 400 (Bad Request)
ErrorCode: InvalidQuery
```

I realized that `properties/created` would work because it's shown in all the query examples above the table.

If `properties.created` is wrong for ordering, probably all the other `properties.*` citings in the table are wrong too.

Probably they should all be `properties/*`, I'm thinking,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3358d737-aaae-d077-1cd7-5479ff077a91
* Version Independent ID: 3358d737-aaae-d077-1cd7-5479ff077a91
* Content: [Filtering, ordering, and paging of entities](https://learn.microsoft.com/en-us/azure/media-services/latest/filter-order-page-entities-how-to)
* Content Source: [media-services/latest/filter-order-page-entities-how-to.md](https://github.com/MicrosoftDocs/azure-media-services/blob/main/media-services/latest/filter-order-page-entities-how-to.md)
* Service: **media-services**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by IngridAtMicrosoft** [comment]
@Bellarmine-Head Thanks for your input. I have requested assistance from the dev team.
