### ISSUE TITLE
'sample info ballon string' on 'Create live event' screen

### ISSUE THREAD

**Issue by euchungmsft** [MicrosoftDocs/azure-media-services#2]
Hi Team,

I wonder if it's appropriate to report this here, or please feel free to forward this to whom it may concern

On "Create live event" screen on the portal, I see them like this, 'sample info ballon string' for both of 'Output aspect ratio' and 'Output key frame interval'. I believe these need to be changed with more informative ones

![image](https://user-images.githubusercontent.com/20915976/177934854-bc041fc1-befe-498e-8cf4-69e61c47a3fc.png)

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1a69fdc-c1da-4998-b515-4e0a10a27f78
* Version Independent ID: d1a69fdc-c1da-4998-b515-4e0a10a27f78
* Content: [Create a live event](https://docs.microsoft.com/en-us/azure/media-services/latest/live-event-create-how-to?tabs=portal)
* Content Source: [media-services/latest/live-event-create-how-to.md](https://github.com/MicrosoftDocs/azure-media-services/blob/main/media-services/latest/live-event-create-how-to.md)
* Service: **media-services**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by IngridAtMicrosoft** [comment]
@euchungmsft Thanks for letting us know.  I have forwarded to the team that manages the portal interface.

**Comment by IngridAtMicrosoft** [comment]
#please-close
