### ISSUE TITLE
URL with REST tab

### ISSUE THREAD

**Issue by phinawang** [MicrosoftDocs/azure-media-services#4]
Hi team, please kindly check the REST tab content, it with wrong link (connect to Azure CLI page).
https://docs.microsoft.com/en-us/azure/media-services/latest/storage-create-how-to?tabs=rest

correct URL link: https://docs.microsoft.com/en-us/rest/api/storagerp/storage-accounts/create?tabs=HTTP
Have a nice day!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b50897-9250-6a41-1e9e-f0d076e4a231
* Version Independent ID: 94b50897-9250-6a41-1e9e-f0d076e4a231
* Content: [Create an Azure storage account](https://docs.microsoft.com/en-us/azure/media-services/latest/storage-create-how-to?tabs=rest)
* Content Source: [media-services/latest/storage-create-how-to.md](https://github.com/MicrosoftDocs/azure-media-services/blob/main/media-services/latest/storage-create-how-to.md)
* Service: **media-services**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by IngridAtMicrosoft** [comment]
Thank you @phinawang! I will correct that today.

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by phinawang** [comment]
Thanks @IngridAtMicrosoft !
