### ISSUE TITLE
Duration format missing

### ISSUE THREAD

**Issue by MattCoalman** [MicrosoftDocs/azure-media-services#5]
Hello,

The description of the field `Duration` should explain the format used here, and how to convert it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fbb4a01-2363-d116-240a-7c174b87d600
* Version Independent ID: 0fbb4a01-2363-d116-240a-7c174b87d600
* Content: [Azure Media Services v3 input metadata schema](https://docs.microsoft.com/en-us/azure/media-services/latest/input-metadata-schema)
* Content Source: [media-services/latest/input-metadata-schema.md](https://github.com/MicrosoftDocs/azure-media-services/blob/main/media-services/latest/input-metadata-schema.md)
* Service: **media-services**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by IngridAtMicrosoft** [comment]
Hi @MattCoalman. Thank you for your input! There is a link the document to help you understand ISO-8601 formatting.  However, I don't think it was all that helpful, so I will change it so that it links to this. https://en.wikipedia.org/wiki/ISO_8601#Times.

**Comment by MattCoalman** [comment]
Thanks for the quick response @IngridAtMicrosoft.  However, on the wikipedia link, I don't see any representation starting with `PT` (e.q. "Duration": "PT1M10.304S")

**Comment by IngridAtMicrosoft** [comment]
Hi @MattCoalman Please see Duration in the same article. I will adjust the messaging in the article.
https://en.wikipedia.org/wiki/ISO_8601#Durations
