### ISSUE TITLE
Hyperlink to https://media.microsoft.com does not work

### ISSUE THREAD

**Issue by daveapsgithub** [MicrosoftDocs/azure-media-services#6]
The page says "A new Azure Media Services marketing page with a live demonstration of LL-HLS is available now at https://media.microsoft.com/"  When I click on the hyperlink, it goes to https://media.microsoft.com/en-au and this page is blank.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6e97e6f-2383-ddb6-06f7-12763cc3e0e0
* Version Independent ID: c6e97e6f-2383-ddb6-06f7-12763cc3e0e0
* Content: [Azure Media Services v3 release notes](https://docs.microsoft.com/en-au/azure/media-services/latest/release-notes)
* Content Source: [media-services/latest/release-notes.md](https://github.com/MicrosoftDocs/azure-media-services/blob/main/media-services/latest/release-notes.md)
* Service: **media-services**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by johndeu** [comment]
Is it still doing this for you?  We do not have the localization done on this page yet, but I see that it re-routes back to en-us for me.

**Comment by daveapsgithub** [comment]
It is still doing it.

 

The page is entirely blank.

 

Dave

**Comment by johndeu** [comment]
Very odd. I'm unable to repro it in any way on my side...

https://media.microsoft.com/
http://media.azure 

each of those resolve to https://media.microsoft.com/en-us when I alter my browser language settings and location.

**Comment by daveapsgithub** [comment]
It works on Edge, not Chrome. Chrome is reporting a 404 on "https://media.microsoft.com/_next/data/GEwuOHtGomuJ79R0LSteh/en-au.json?lang=en-au"  Maybe it is because I am logged on to some MS service on Chrome and not Edge?

**Comment by IngridAtMicrosoft** [comment]
@johndeu Was this issue resolved?

**Comment by johndeu** [comment]
I was not able to repro it myself... I'm not sure if it was unique to @daveapsgithub and his Chrome plugin setup.

**Comment by IngridAtMicrosoft** [comment]
> I was not able to repro it myself... I'm not sure if it was unique to @daveapsgithub and his Chrome plugin setup.

Thanks.

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by daveapsgithub** [comment]
Definitely not fixed.  Chrome dev window attached.   A friend of mine (also in Australia) is reporting the same.

![image](https://user-images.githubusercontent.com/5207604/210688034-e6cdd37c-2c48-4883-b0fb-4bb3397b9aa4.png)

**Comment by johndeu** [comment]
Keep open @IngridAtMicrosoft  - I think I have found a repro.

In Chrome, it appears that in the Application local storage, the next.js locale language is being set in the "lng" property.  If I change that to be 'en-au' and then load the root http://media.azure  then the next.js framework is redirecting to /en-au and not landing on the /en-us 

We are looking to see why that is happening.  I think it is a simple config setting for non explicit supported languages. 
Looking into this library - https://github.com/i18next/next-i18next#fallback-locales  

Thanks @daveapsgithub  for helping with this. We will figure it out.

**Comment by johndeu** [comment]
@daveapsgithub  - we made a fix that appears to have solved it when we alter the language of the Chrome browser to Australian.  Can you give it another check for us.

**Comment by daveapsgithub** [comment]
Fixed! :)

**Comment by johndeu** [comment]
Awesome! Thanks @daveapsgithub  for flagging this for us.  Took a while to figure out the glitch... ended up being a very simple setting that was missing on the config file.
