### ISSUE TITLE
CreateMediaServicesClientAsync set up incorrectly

### ISSUE THREAD

**Issue by JosephBerm** [MicrosoftDocs/azure-media-services#7]
[Enter feedback here]
In the following function:
```c#
public static async Task<IAzureMediaServicesClient> CreateMediaServicesClientAsync(ConfigWrapper config, bool interactive = false)
{
    ServiceClientCredentials credentials;
    if (interactive)
        credentials = await GetCredentialsInteractiveAuthAsync(config);
    else
        credentials = await GetCredentialsAsync(config);

    return new AzureMediaServicesClient(config.ArmEndpoint, credentials)
    {
        SubscriptionId = config.SubscriptionId,
    };
}
```

The return of AzureMediaServicesClient does not need the **ArmEndpoint** parameter. Instead, it needs `credentials` and a `DelegatingHandler`.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdf9b00-1c70-2464-67e3-bcf377379fed
* Version Independent ID: dbdf9b00-1c70-2464-67e3-bcf377379fed
* Content: [Upload, encode, and stream with Media Services v3](https://docs.microsoft.com/en-us/azure/media-services/latest/stream-files-tutorial-with-api?source=recommendations)
* Content Source: [media-services/latest/stream-files-tutorial-with-api.md](https://github.com/MicrosoftDocs/azure-media-services/blob/main/media-services/latest/stream-files-tutorial-with-api.md)
* Service: **media-services**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by IngridAtMicrosoft** [comment]
@JosephBerm Thank you for your feedback. This article has been retired. #please-close

**Comment by IngridAtMicrosoft** [comment]
@JosephBerm Please close this issue.
