### ISSUE TITLE
HLS-V4 is format=m3u8-aapl or format=m3u8-aapl-v4

### ISSUE THREAD

**Issue by EmmanuelEngel** [MicrosoftDocs/azure-media-services#8]
I fail to read my content with some to the provided url here. What I do not understrand is the difference with another part of the documentation.
According to https://docs.microsoft.com/en-us/azure/media-services/latest/encode-dynamic-packaging-concept#hls-dynamic-packaging =>
  HLS-CMAF => format=m3u8-cmaf
  HLS-V4 => format=m3u8-aapl
  HLS-V3 => format=m3u8-aapl-v3

And here 
  HLS-CMAF => format=m3u8-cmaf,encryption=...
  HLS-V4 => format=m3u8-aapl-v4,encryption=...
  HLS-V3 => format=m3u8-aapl-v3,encryption=...
  
  In my case, can't stream using m3u8-aapl-v4
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ce06721-d3f7-72d9-c4be-2217af04d2b5
* Version Independent ID: 3ce06721-d3f7-72d9-c4be-2217af04d2b5
* Content: [Low latency streaming protocols and encryption types](https://docs.microsoft.com/en-us/azure/media-services/latest/drm-streaming-protocol-encryption-types-reference#hls-and-dash)
* Content Source: [media-services/latest/drm-streaming-protocol-encryption-types-reference.md](https://github.com/MicrosoftDocs/azure-media-services/blob/main/media-services/latest/drm-streaming-protocol-encryption-types-reference.md)
* Service: **media-services**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by IngridAtMicrosoft** [comment]
@EmmanuelEngel I apologize for the delay in addressing your issue. Were you able to understand the URL parameters better?

**Comment by IngridAtMicrosoft** [comment]
@EmmanuelEngel Please close this issue if you were able to solve your problem.
